"""
Auto-generated Test Case (Selenium)
Generated by Test Capture Tool
"""

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pytest


def test_recorded_actions():
    """Test case generated from recorded user interactions"""
    chrome_options = Options()
    chrome_options.add_argument("--start-maximized")
    chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
    chrome_options.add_experimental_option('useAutomationExtension', False)
    
    driver = webdriver.Chrome(options=chrome_options)
    
    try:
        driver.get('https://qa-exchange.doceree.com/login')
        assert 'Doceree - Login' in driver.title

        driver.get('https://qa-exchange.doceree.com/login')
        assert 'Doceree - Login' in driver.title

        driver.get('https://qa-exchange.doceree.com/login')
        assert 'Doceree - Login' in driver.title

        driver.get('https://qa-exchange.doceree.com/login')
        assert 'Doceree - Login' in driver.title

    finally:
        driver.quit()


if __name__ == "__main__":
    test_recorded_actions()
