"""
Auto-generated Test Case
Generated by Test Capture Tool
"""

from playwright.sync_api import sync_playwright
import pytest


def test_recorded_actions():
    """Test case generated from recorded user interactions"""
    with sync_playwright() as p:
        # Launch browser
        browser = p.chromium.launch(headless=False)
        context = browser.new_context(viewport={"width": 1920, "height": 1080})
        page = context.new_page()
        
        try:
            # Navigate to: https://qa-exchange.doceree.com/login
            page.goto('https://qa-exchange.doceree.com/login', wait_until='networkidle')
            assert page.title() == 'Doceree - Login'

            # Page capture: Doceree - Login
            page.goto('https://qa-exchange.doceree.com/login', wait_until='networkidle')
            # Verify page loaded
            assert 'Doceree - Login' in page.title()

            # Page capture: Doceree - Login
            page.goto('https://qa-exchange.doceree.com/login', wait_until='networkidle')
            # Verify page loaded
            assert 'Doceree - Login' in page.title()

            # Page capture: Doceree - Login
            page.goto('https://qa-exchange.doceree.com/login', wait_until='networkidle')
            # Verify page loaded
            assert 'Doceree - Login' in page.title()

        finally:
            context.close()
            browser.close()


if __name__ == "__main__":
    test_recorded_actions()
